services:
  backend:
    build: ./backend
    container_name: denttime_backend
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000
      - MODEL_NAME=DentTimeModel
      - MODEL_STAGE=Production

  frontend:
    build: ./frontend
    container_name: denttime_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000