FROM apache/airflow:2.9.0-python3.11

USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends git libgomp1 \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements-airflow.txt /requirements-airflow.txt
RUN pip install --no-cache-dir -r /requirements-airflow.txt

RUN mkdir -p /opt/airflow/project
ENV PYTHONPATH=/opt/airflow/project
